Quantitative Investing with Pandas in Python

In [1]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [2]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [3]:
import numpy as np
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]

In [4]:
b = np.ones((1,2))
print(b)

[[1. 1.]]

In [5]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]

In [6]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]

In [7]:
e = np.random.random((2,2))
print (e)

[[0.1771108  0.54765107]
 [0.66984832 0.36262786]]

In [9]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(a.shape)

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.dtype.name

'int64'

In [13]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [18]:
a = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [19]:
print(a.ndim)

2

In [20]:
print(a.shape)

(3, 4)

PYTHON PANDAS

In [21]:
import pandas as pd
df = pd.DataFrame({"a": [4, 5, 6],
"b": [7, 8, 9],
"c": [10, 11, 12]},
index = [1, 2, 3])

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported

In [24]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [25]:
dates = pd.date_range('20181001',
periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [26]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2018-10-01 -1.496003 -0.367340 -2.444782 -0.582857
2018-10-02  2.160336  0.118833  0.634628 -1.454564
2018-10-03  0.292962 -0.831817 -1.758453 -0.630509
2018-10-04 -0.039390 -0.015928  0.069668  0.359323
2018-10-05 -1.090973 -1.286276 -2.332628  0.394562
2018-10-06  1.505587  2.434931  0.367922  0.277474

In [27]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

                 A         B         C         D         E
student1  0.336465 -0.010080  1.082610  0.394609 -0.251067
student2 -0.337569  0.011578 -0.121835  0.008489 -1.205615
student3  0.163965 -0.415394  1.621343  0.538541 -0.048216

In [28]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [29]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

Python Pandas for Finance

# !pip install pandas_datareader

In [1]:
import yfinance as yf
import pandas as pd
import datetime as dt

#Read Stock Data from Yahoo Finance

In [31]:
end = dt.datetime(2017, 12, 31)
start = dt.datetime(2016, 1, 1)

In [35]:
pip install yfinance

Requirement already satisfied: yfinance in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (2.3.1)
Requirement already satisfied: numpy>=1.16.5 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (2.3.1)
Requirement already satisfied: requests>=2.31 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (6.32.1)
Requirement already satisfied: websockets>=13.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.14.1)
Requirement already satisfied: cffi>=1.12.0 in /home/codespace/.local/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /home/codespace/.local/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance) (2025.7.9)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.5.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
%matplotlib inline

In [8]:
#Read Stock Data from Yahoo Finance
end = dt.datetime.now()